### ISSUE TITLE
프로젝트

### ISSUE THREAD

**Issue by pjh9362** [17-1-SKKU-OSS/158A#1]
제안해주세요

**Comment by halfways** [comment]
네 감사합니다 :)

2017-04-18 19:19 GMT+09:00 Park Joohong <notifications@github.com>:

**Comment by jeddchoi** [comment]
https://github.com/ellisonleao/clumsy-bird
이거 flappy bird인데 유저맵을 만들고 한국어 번역 하는거 어떠세요?

**Comment by jeddchoi** [comment]
https://github.com/doublespeakgames/adarkroom
Web game , javascript
