### ISSUE TITLE
A Dark Room 게임 엔딩을 봤습니다.(게임 개선할 점)

### ISSUE THREAD

**Issue by jeddchoi** [17-1-SKKU-OSS/158A#2]
![default](https://cloud.githubusercontent.com/assets/26888111/26312782/ab298742-3f43-11e7-8087-e98355b0e77f.PNG)

이 게임은 스토리가 있기 보다는 마을 육성 시뮬레이션 게임에 가까운 것같습니다.
일꾼이 자원을 계속 캐고, 그 자원으로 무기와 약품을 비롯해서 물품을 얻은 후, 탐험을 떠날 수가 있습니다.
탐험 중에 무작위로 마주치는 적들과 무기로 싸우게 되고 보상을 얻어서 돌아올 수도 있고, 자원이 떨어져 무기를 다 잃어버리는 경우도 있습니다. 그리고 외계합금이라는 물질이 도중에 발견되는데 그것으로 미니게임인 우주선 이륙게임의 선체강화 및 엔진 업그레이드를 하게 됩니다. 그래서 끝까지 성공하게 되면 윗 사진과 같이 결과가 나오면서 끝나게 됩니다.
게임 도중에 세이브 기능이 있어서 다른 기기에서 이어서 할 수 있고(어떤 방식으로 이어지는지는 모르겠습니다.) 속도를 2배 빠르게 할 수 있는 모드, 화면을 어둡게 하는 모드로 설정할 수 있습니다.

개선할 점으로는
1. 브라우저에 따라, 기기에 따라 화면 표시되는 것이 짤리는 것이 있습니다.
PC-크롬 브라우저를 사용해서 게임을 했는데 아이템 버튼이 짤려서 게임 진행이 안되다가
세이브기능을 통해서 새로운 창에서 이어서 했더니 모든 버튼이 다 보여서 계속해서 진행할 수 있었습니다.

2. 메시지가 뜰때마다 아주 짧은 알림음이 울리면 어떨까 싶습니다.
분명히 의미 있는 메시지가 있는데 그것들이 의미 없는 메시지에 가려서 확인을 못하고 넘겨지는 경우가 있습니다. 그래서 의미 없는 메시지는 없애버리고 의미 있는 메시지가 뜰때 딩동 같은 알림음이 있으면 좋을것 같습니다.

3. 모든 버튼을 마우스로 조작해야 하는데 키보드의 키를 이용해서 단축키처럼 버튼을 사용할 수 있게 하면 좋을 것 같습니다. 특히, 탐험맵에서 적들과 마주치게 되었을때 무기를 광클해야 해서 조금 불편했습니다.

4. 지금까지 읽은 메시지와 새로 뜬 메시지를 구분해서 표시해주면 좋겠습니다.
메시지가 많이 뜨기 때문에 한 눈에 구분하기가 어렵습니다.

5. 창고의 자원에 마우스 커서를 올리게 되면 스탯이 뜨게 되는데 글자에 정확하게 올려야지 보입니다. 그래서 마우스를 정확하게 위치해야 되서 불편합니다.

일단 이정도 생각나는대로 작성해보았습니다.
추가적으로 개선할 점이 있으면 여기다가 올리겠습니다.

**Comment by skkukjh** [comment]
몇몇 그래픽들이 직관성이 떨어지는 문제가 있는 것 같습니다.
가령, 자원들 수량을 확인할 때, 모든 자원이 동일한 색상의 텍스트로만 적혀 있어서
필요한 자원이 얼마만큼 있는지 한 눈에 확인하기 어렵습니다.
게임의 전체적인 컨셉상 큰 변경은 곤란하다 하더라도
각 자원을 상징하는 아스키 기호나 색상을 이용해서 개선하는 방안을 제안해보면 어떨까요?

**Comment by jeddchoi** [comment]
오 좋네요. 그러니까 10단위는 점, 100단위는 동그라미, 1000단위는 @, 10000단위는 별표 이런식으로 수량을 나타내는 걸 의미하시는건가요?
